/**
 * @description       : 
 * @author            : SkyPlanner - Dianelys Velazquez
 * @group             : 
 * @last modified on  : 09-09-2024
 * @last modified by  : SkyPlanner - Dianelys Velazquez
**/
public with sharing class Constants 
{
    public static final String LOGGER_OPTIMOVE_API_CATEGORY = 'Optimove-API-Integration';

    public static final String OPTIMOVE_GET_ATTRIBUTES_ENDPOINT = 'Optimove_Api_Get_Attributes_Endpoint';
    public static final String OPTIMOVE_UPDATE_ATTRIBUTES_ENDPOINT = 'Optimove_Api_Update_Attributes_Endpoint';
    public static final String OPTIMOVE_PREFERENCES_ENDPOINT = 'Optimove_Api_Preferences_Endpoint';
    public static final String OPTIMOVE_CHECK_PREFERENCE_CHANNELS = 'Optimove_Check_Preference_Channels';
    public static final String OPTIMOVE_CALLBACK_SITE_NAME = 'Optimove_Callback_Site_Name';
}